### ISSUE TITLE
Double click Result to see in popup (for results that are too long)

### ISSUE THREAD

**Issue by thomas-optimove** [En3Tho/PoshRedisViewer#9]
The `Results` panel shows in a listbox the contents of a Redis Key.

If this is too wide for the console (e.g. when RedisString is long) then it is not possible to see all the content.  In my case the key value stored in Redis is a serialized json object so quite long.

It would be really cool if you could double click or hit Enter in the listbox and have a modal popup show the content in a word wrapped popup (e.g. `TextView`).

**Comment by En3Tho** [comment]
It's a good idea but I'm not sure I want to do this. Simply a lack of time/interest because I'm not using Redis that much lately.

I did this project because it was a good workhorse at my previous work place and I liked the fact that I could use it on both Win and Linux and from directly from terminal. E.g. kubectl port forward and then get-redisviewer and voila.

Now to the main point. Are you interested in learning some F#? :D

**Comment by thomas-optimove** [comment]
Sure I'll give it a go.  Will be nice to dip my toe in some F#.  But will have to be a weekends/evenings project 🌔 

I'll work on a PR.

**Comment by En3Tho** [comment]
Nice! F# can teach you a lot (well, it made me better I believe). Feel free to ask any questions!
